### ISSUE TITLE
Fess 11.2.0 fails to start

### ISSUE THREAD

**Issue by micakovic** [codelibs/fess#1113]
Testing an upgrade to 11.2.0, Tomcat fails to start:

```
2017-06-19 10:11:17,184 [localhost-startStop-1] ERROR Failed to initialize Lasta Di.
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
app.xml

[Namespace]
null
* * * * * * * * * */
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81) ~[lastaflute-0.9.8.jar:?]
        at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45) ~[lastaflute-0.9.8.jar:?]
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:136) [lastaflute-0.9.8.jar:?]
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94) [lastaflute-0.9.8.jar:?]
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285) [classes/:?]
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266) [classes/:?]
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108) [classes/:?]
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4590) [classes/:?]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233) [classes/:?]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [classes/:?]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [classes/:?]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [classes/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(init) of org.codelibs.fess.helper.QueryHelper, because org.lastaflute.core.direction.exception.ConfigPropertyNotFoundException: L
ook! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Not found the configuration property by the key.

[NotFound Property]
index.field.thumbnail

[Config Display]
FessConfig$SimpleImpl:{fess_config.properties, [fess_env_web.properties], ObjectiveConfig$1:{JavaPropertiesResult:{[domain.title, elasticsearch.cluster.name, elasticsearch.http.url, elasticsearch.transport.sniff, elasticsearch.transport.pi
ng_timeout, elasticsearch.transport.nodes_sampler_interval, app.cipher.algorism, app.cipher.key, app.digest.algorism, jvm.crawler.options, jvm.suggest.options, job.system.job.ids, job.template.title.web, job.template.title.file, job.templa
te.title.data, job.template.script, java.command.path, path.encoding, use.own.tmp.dir, max.log.output.length, supported.uploaded.js.extentions, supported.uploaded.css.extentions, supported.uploaded.media.extentions, supported.uploaded.file
s, supported.languages, api.access.token.length, api.access.token.required, crawler.document.max.site.length, crawler.document.site.encoding, crawler.document.unknown.hostname, crawler.document.use.site.encoding.on.english, crawler.documen
t.append.data, crawler.document.max.alphanum.term.size, crawler.document.max.symbol.term.size, crawler.document.duplicate.term.removed, crawler.document.space.chars, crawler.crawling.data.encoding, crawler.web.protocols, crawler.file.proto
cols, crawler.ignore.robots.txt, crawler.ignore.meta.robots, crawler.ignore.content.exception, crawler.metadata.content.excludes, crawler.metadata.name.mapping, crawler.document.html.content.xpath, crawler.document.html.lang.xpath, crawler
.document.html.digest.xpath, crawler.document.html.canonical.xpath, crawler.document.html.pruned.tags, crawler.document.html.max.digest.length, crawler.document.file.name.encoding, crawler.document.file.no.title.label, crawler.document.fil
e.ignore.empty.content, crawler.document.file.max.title.length, crawler.document.file.max.digest.length, crawler.document.file.append.meta.content, crawler.document.file.append.body.content, crawler.document.file.default.lang, crawler.docu
ment.cache.enabled, crawler.document.cache.max.size, crawler.document.cache.supported.mimetypes, crawler.document.cache.html.mimetypes, indexer.thread.dump.enabled, indexer.unprocessed.document.size, indexer.click.count.enabled, indexer.fa
vorite.count.enabled, indexer.webfs.commit.margin.time, indexer.webfs.max.empty.list.count, indexer.webfs.update.interval, indexer.webfs.max.document.cache.size, indexer.webfs.max.document.request.size, indexer.data.max.document.cache.size
, indexer.data.max.document.request.size, index.field.favorite_count, index.field.click_count, index.field.config_id, index.field.expires, index.field.url, index.field.doc_id, index.field.id, index.field.version, index.field.lang, index.fi
eld.has_cache, index.field.last_modified, index.field.anchor, index.field.segment, index.field.role, index.field.boost, index.field.created, index.field.timestamp, index.field.label, index.field.mimetype, index.field.parent_id, index.field
.important_content, index.field.content, index.field.cache, index.field.digest, index.field.title, index.field.host, index.field.site, index.field.content_length, index.field.filetype, index.field.filename, response.field.content_title, re
sponse.field.content_description, response.field.url_link, response.field.site_path, index.document.search.index, index.document.update.index, index.document.type, index.document.suggest.index, index.document.crawler.index, index.admin.arr
ay.fields, index.admin.date.fields, index.admin.integer.fields, index.admin.long.fields, index.admin.float.fields, index.admin.double.fields, index.admin.required.fields, index.search.timeout, index.scroll.search.timeout.timeout, index.ind
ex.timeout, index.bulk.timeout, index.delete.timeout, index.health.timeout, index.indices.timeout, query.max.length, query.geo.fields, query.browser.lang.parameter.name, query.replace.term.with.prefix.query, query.highlight.fragment.size, 
query.highlight.number.of.fragments, query.highlight.type, query.max.search.result.offset, query.additional.response.fields, query.additional.api.response.fields, query.additional.cache.response.fields, query.additional.highlighted.fields,
 query.additional.search.fields, query.additional.facet.fields, query.additional.sort.fields, query.additional.not.analyzed.fields, query.default.languages, query.language.mapping, query.boost.title, query.boost.title.lang, query.boost.con
tent, query.boost.content.lang, smb.role.from.file, smb.available.sid.types, index.backup.targets, form.admin.max.input.size, authentication.admin.users, authentication.admin.roles, role.search.default.permissions, role.search.default.disp
lay.permissions, role.search.guest.permissions, role.search.user.prefix, role.search.group.prefix, role.search.role.prefix, cookie.default.path, cookie.default.expire, cookie.eternal.expire, cookie.remember.me.harbor.key, paging.page.size,
 paging.page.range.size, paging.page.range.fill.limit, page.docboost.max.fetch.size, page.keymatch.max.fetch.size, page.labeltype.max.fetch.size, page.roletype.max.fetch.size, page.user.max.fetch.size, page.role.max.fetch.size, page.group.
max.fetch.size, page.crawling.info.param.max.fetch.size, page.crawling.info.max.fetch.size, page.data.config.max.fetch.size, page.web.config.max.fetch.size, page.file.config.max.fetch.size, page.duplicate.host.max.fetch.size, page.failure.
url.max.fetch.size, page.favorite.log.max.fetch.size, page.file.auth.max.fetch.size, page.web.auth.max.fetch.size, page.path.mapping.max.fetch.size, page.request.header.max.fetch.size, page.scheduled.job.max.fetch.size, page.search.field.l
og.max.fetch.size, page.elevate.word.max.fetch.size, page.bad.word.max.fetch.size, page.dictionary.max.fetch.size, page.thumbnail.queue.max.fetch.size, paging.search.page.start, paging.search.page.size, paging.search.page.max.size, thumbna
il.html.phantomjs.enabled, thumbnail.html.phantomjs.max.height, thumbnail.html.phantomjs.keep.alive, thumbnail.html.phantomjs.window.width, thumbnail.html.phantomjs.window.height, thumbnail.html.phantomjs.thumbnail.width, thumbnail.html.ph
antomjs.thumbnail.height, thumbnail.html.phantomjs.format, thumbnail.generator.targets, thumbnail.crawler.enabled, mail.from.name, mail.from.address, scheduler.target.name, scheduler.job.class, scheduler.concurrent.exec.mode, scheduler.mon
itor.interval, online.help.base.link, online.help.name.failureurl, online.help.name.elevateword, online.help.name.reqheader, online.help.name.dict.synonym, online.help.name.dict, online.help.name.dict.kuromoji, online.help.name.dict.seunje
on, online.help.name.dict.protwords, online.help.name.dict.mapping, online.help.name.webconfig, online.help.name.searchlist, online.help.name.log, online.help.name.general, online.help.name.role, online.help.name.joblog, online.help.name.k
eymatch, online.help.name.wizard, online.help.name.badword, online.help.name.pathmap, online.help.name.boostdoc, online.help.name.dataconfig, online.help.name.systeminfo, online.help.name.user, online.help.name.group, online.help.name.desi
gn, online.help.name.dashboard, online.help.name.webauth, online.help.name.fileconfig, online.help.name.fileauth, online.help.name.labeltype, online.help.name.duplicatehost, online.help.name.scheduler, online.help.name.crawlinginfo, online
.help.name.backup, online.help.name.upgrade, online.help.name.esreq, online.help.name.accesstoken, online.help.name.suggest, online.help.supported.langs, suggest.popular.word.seed, suggest.popular.word.tags, suggest.popular.word.fields, su
ggest.popular.word.excludes, suggest.popular.word.size, suggest.popular.word.window.size, suggest.min.hit.count, suggest.field.contents, suggest.field.tags, suggest.field.roles, suggest.field.index.contents, suggest.update.request.interval
, suggest.update.contents.limit.num.percentage, suggest.update.contents.limit.num, suggest.source.reader.scroll.size, suggest.popular.word.cache.size, suggest.popular.word.cache.expire, suggest.search.log.permissions, ldap.admin.enabled, l
dap.admin.user.filter, ldap.admin.user.base.dn, ldap.admin.user.object.classes, ldap.admin.role.filter, ldap.admin.role.base.dn, ldap.admin.role.object.classes, ldap.admin.group.filter, ldap.admin.group.base.dn, ldap.admin.group.object.cla
sses, ldap.admin.sync.password, ldap.max.username.length, ldap.role.search.user.enabled, ldap.role.search.group.enabled, ldap.role.search.role.enabled, ldap.attr.surname, ldap.attr.givenName, ldap.attr.employeeNumber, ldap.attr.mail, ldap.
attr.telephoneNumber, ldap.attr.homePhone, ldap.attr.homePostalAddress, ldap.attr.labeledURI, ldap.attr.roomNumber, ldap.attr.description, ldap.attr.title, ldap.attr.pager, ldap.attr.street, ldap.attr.postalCode, ldap.attr.physicalDelivery
OfficeName, ldap.attr.destinationIndicator, ldap.attr.internationaliSDNNumber, ldap.attr.state, ldap.attr.employeeType, ldap.attr.facsimileTelephoneNumber, ldap.attr.postOfficeBox, ldap.attr.initials, ldap.attr.carLicense, ldap.attr.mobile
, ldap.attr.postalAddress, ldap.attr.city, ldap.attr.teletexTerminalIdentifier, ldap.attr.x121Address, ldap.attr.businessCategory, ldap.attr.registeredAddress, ldap.attr.displayName, ldap.attr.preferredLanguage, ldap.attr.departmentNumber,
 ldap.attr.uidNumber, ldap.attr.gidNumber, ldap.attr.homeDirectory, sso.type, spnego.logger.level, spnego.krb5.conf, spnego.login.conf, spnego.preauth.username, spnego.preauth.password, spnego.login.client.module, spnego.login.server.modul
e, spnego.allow.basic, spnego.allow.unsecure.basic, spnego.prompt.ntlm, spnego.allow.localhost, spnego.allow.delegation, oic.client.id, oic.client.secret, oic.auth.server.url, oic.redirect.url, oic.scope, oic.token.server.url, oic.default.
roles, oic.default.groups, lasta_di.smart.deploy.mode, development.here, environment.title, framework.debug, time.adjust.time.millis, mail.send.mock, mail.smtp.server.main.host.and.port, mail.subject.test.prefix, mail.return.path]}}}@5042a
93b
* * * * * * * * * */
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:83) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.4.jar:?]
        ... 17 more
Caused by: org.lastaflute.core.direction.exception.ConfigPropertyNotFoundException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Not found the configuration property by the key.

[NotFound Property]
index.field.thumbnail

[Config Display]
FessConfig$SimpleImpl:{fess_config.properties, [fess_env_web.properties], ObjectiveConfig$1:{JavaPropertiesResult:{[domain.title, elasticsearch.cluster.name, elasticsearch.http.url, elasticsearch.transport.sniff, elasticsearch.transport.pi
ng_timeout, elasticsearch.transport.nodes_sampler_interval, app.cipher.algorism, app.cipher.key, app.digest.algorism, jvm.crawler.options, jvm.suggest.options, job.system.job.ids, job.template.title.web, job.template.title.file, job.templa
te.title.data, job.template.script, java.command.path, path.encoding, use.own.tmp.dir, max.log.output.length, supported.uploaded.js.extentions, supported.uploaded.css.extentions, supported.uploaded.media.extentions, supported.uploaded.file
s, supported.languages, api.access.token.length, api.access.token.required, crawler.document.max.site.length, crawler.document.site.encoding, crawler.document.unknown.hostname, crawler.document.use.site.encoding.on.english, crawler.documen
t.append.data, crawler.document.max.alphanum.term.size, crawler.document.max.symbol.term.size, crawler.document.duplicate.term.removed, crawler.document.space.chars, crawler.crawling.data.encoding, crawler.web.protocols, crawler.file.proto
cols, crawler.ignore.robots.txt, crawler.ignore.meta.robots, crawler.ignore.content.exception, crawler.metadata.content.excludes, crawler.metadata.name.mapping, crawler.document.html.content.xpath, crawler.document.html.lang.xpath, crawler
.document.html.digest.xpath, crawler.document.html.canonical.xpath, crawler.document.html.pruned.tags, crawler.document.html.max.digest.length, crawler.document.file.name.encoding, crawler.document.file.no.title.label, crawler.document.fil
e.ignore.empty.content, crawler.document.file.max.title.length, crawler.document.file.max.digest.length, crawler.document.file.append.meta.content, crawler.document.file.append.body.content, crawler.document.file.default.lang, crawler.docu
ment.cache.enabled, crawler.document.cache.max.size, crawler.document.cache.supported.mimetypes, crawler.document.cache.html.mimetypes, indexer.thread.dump.enabled, indexer.unprocessed.document.size, indexer.click.count.enabled, indexer.fa
vorite.count.enabled, indexer.webfs.commit.margin.time, indexer.webfs.max.empty.list.count, indexer.webfs.update.interval, indexer.webfs.max.document.cache.size, indexer.webfs.max.document.request.size, indexer.data.max.document.cache.size
, indexer.data.max.document.request.size, index.field.favorite_count, index.field.click_count, index.field.config_id, index.field.expires, index.field.url, index.field.doc_id, index.field.id, index.field.version, index.field.lang, index.fi
eld.has_cache, index.field.last_modified, index.field.anchor, index.field.segment, index.field.role, index.field.boost, index.field.created, index.field.timestamp, index.field.label, index.field.mimetype, index.field.parent_id, index.field
.important_content, index.field.content, index.field.cache, index.field.digest, index.field.title, index.field.host, index.field.site, index.field.content_length, index.field.filetype, index.field.filename, response.field.content_title, re
sponse.field.content_description, response.field.url_link, response.field.site_path, index.document.search.index, index.document.update.index, index.document.type, index.document.suggest.index, index.document.crawler.index, index.admin.arr
ay.fields, index.admin.date.fields, index.admin.integer.fields, index.admin.long.fields, index.admin.float.fields, index.admin.double.fields, index.admin.required.fields, index.search.timeout, index.scroll.search.timeout.timeout, index.ind
ex.timeout, index.bulk.timeout, index.delete.timeout, index.health.timeout, index.indices.timeout, query.max.length, query.geo.fields, query.browser.lang.parameter.name, query.replace.term.with.prefix.query, query.highlight.fragment.size, 
query.highlight.number.of.fragments, query.highlight.type, query.max.search.result.offset, query.additional.response.fields, query.additional.api.response.fields, query.additional.cache.response.fields, query.additional.highlighted.fields,
 query.additional.search.fields, query.additional.facet.fields, query.additional.sort.fields, query.additional.not.analyzed.fields, query.default.languages, query.language.mapping, query.boost.title, query.boost.title.lang, query.boost.con
tent, query.boost.content.lang, smb.role.from.file, smb.available.sid.types, index.backup.targets, form.admin.max.input.size, authentication.admin.users, authentication.admin.roles, role.search.default.permissions, role.search.default.disp
lay.permissions, role.search.guest.permissions, role.search.user.prefix, role.search.group.prefix, role.search.role.prefix, cookie.default.path, cookie.default.expire, cookie.eternal.expire, cookie.remember.me.harbor.key, paging.page.size,
 paging.page.range.size, paging.page.range.fill.limit, page.docboost.max.fetch.size, page.keymatch.max.fetch.size, page.labeltype.max.fetch.size, page.roletype.max.fetch.size, page.user.max.fetch.size, page.role.max.fetch.size, page.group.
max.fetch.size, page.crawling.info.param.max.fetch.size, page.crawling.info.max.fetch.size, page.data.config.max.fetch.size, page.web.config.max.fetch.size, page.file.config.max.fetch.size, page.duplicate.host.max.fetch.size, page.failure.
url.max.fetch.size, page.favorite.log.max.fetch.size, page.file.auth.max.fetch.size, page.web.auth.max.fetch.size, page.path.mapping.max.fetch.size, page.request.header.max.fetch.size, page.scheduled.job.max.fetch.size, page.search.field.l
og.max.fetch.size, page.elevate.word.max.fetch.size, page.bad.word.max.fetch.size, page.dictionary.max.fetch.size, page.thumbnail.queue.max.fetch.size, paging.search.page.start, paging.search.page.size, paging.search.page.max.size, thumbna
il.html.phantomjs.enabled, thumbnail.html.phantomjs.max.height, thumbnail.html.phantomjs.keep.alive, thumbnail.html.phantomjs.window.width, thumbnail.html.phantomjs.window.height, thumbnail.html.phantomjs.thumbnail.width, thumbnail.html.ph
antomjs.thumbnail.height, thumbnail.html.phantomjs.format, thumbnail.generator.targets, thumbnail.crawler.enabled, mail.from.name, mail.from.address, scheduler.target.name, scheduler.job.class, scheduler.concurrent.exec.mode, scheduler.mon
itor.interval, online.help.base.link, online.help.name.failureurl, online.help.name.elevateword, online.help.name.reqheader, online.help.name.dict.synonym, online.help.name.dict, online.help.name.dict.kuromoji, online.help.name.dict.seunje
on, online.help.name.dict.protwords, online.help.name.dict.mapping, online.help.name.webconfig, online.help.name.searchlist, online.help.name.log, online.help.name.general, online.help.name.role, online.help.name.joblog, online.help.name.k
eymatch, online.help.name.wizard, online.help.name.badword, online.help.name.pathmap, online.help.name.boostdoc, online.help.name.dataconfig, online.help.name.systeminfo, online.help.name.user, online.help.name.group, online.help.name.desi
gn, online.help.name.dashboard, online.help.name.webauth, online.help.name.fileconfig, online.help.name.fileauth, online.help.name.labeltype, online.help.name.duplicatehost, online.help.name.scheduler, online.help.name.crawlinginfo, online
.help.name.backup, online.help.name.upgrade, online.help.name.esreq, online.help.name.accesstoken, online.help.name.suggest, online.help.supported.langs, suggest.popular.word.seed, suggest.popular.word.tags, suggest.popular.word.fields, su
ggest.popular.word.excludes, suggest.popular.word.size, suggest.popular.word.window.size, suggest.min.hit.count, suggest.field.contents, suggest.field.tags, suggest.field.roles, suggest.field.index.contents, suggest.update.request.interval
, suggest.update.contents.limit.num.percentage, suggest.update.contents.limit.num, suggest.source.reader.scroll.size, suggest.popular.word.cache.size, suggest.popular.word.cache.expire, suggest.search.log.permissions, ldap.admin.enabled, l
dap.admin.user.filter, ldap.admin.user.base.dn, ldap.admin.user.object.classes, ldap.admin.role.filter, ldap.admin.role.base.dn, ldap.admin.role.object.classes, ldap.admin.group.filter, ldap.admin.group.base.dn, ldap.admin.group.object.cla
sses, ldap.admin.sync.password, ldap.max.username.length, ldap.role.search.user.enabled, ldap.role.search.group.enabled, ldap.role.search.role.enabled, ldap.attr.surname, ldap.attr.givenName, ldap.attr.employeeNumber, ldap.attr.mail, ldap.
attr.telephoneNumber, ldap.attr.homePhone, ldap.attr.homePostalAddress, ldap.attr.labeledURI, ldap.attr.roomNumber, ldap.attr.description, ldap.attr.title, ldap.attr.pager, ldap.attr.street, ldap.attr.postalCode, ldap.attr.physicalDelivery
OfficeName, ldap.attr.destinationIndicator, ldap.attr.internationaliSDNNumber, ldap.attr.state, ldap.attr.employeeType, ldap.attr.facsimileTelephoneNumber, ldap.attr.postOfficeBox, ldap.attr.initials, ldap.attr.carLicense, ldap.attr.mobile
, ldap.attr.postalAddress, ldap.attr.city, ldap.attr.teletexTerminalIdentifier, ldap.attr.x121Address, ldap.attr.businessCategory, ldap.attr.registeredAddress, ldap.attr.displayName, ldap.attr.preferredLanguage, ldap.attr.departmentNumber,
 ldap.attr.uidNumber, ldap.attr.gidNumber, ldap.attr.homeDirectory, sso.type, spnego.logger.level, spnego.krb5.conf, spnego.login.conf, spnego.preauth.username, spnego.preauth.password, spnego.login.client.module, spnego.login.server.modul
e, spnego.allow.basic, spnego.allow.unsecure.basic, spnego.prompt.ntlm, spnego.allow.localhost, spnego.allow.delegation, oic.client.id, oic.client.secret, oic.auth.server.url, oic.redirect.url, oic.scope, oic.token.server.url, oic.default.
roles, oic.default.groups, lasta_di.smart.deploy.mode, development.here, environment.title, framework.debug, time.adjust.time.millis, mail.send.mock, mail.smtp.server.main.host.and.port, mail.subject.test.prefix, mail.return.path]}}}@5042a
93b
* * * * * * * * * */
        at org.lastaflute.core.direction.ObjectiveConfig.verifyPropertyValue(ObjectiveConfig.java:162) ~[lastaflute-0.9.8.jar:?]
        at org.lastaflute.core.direction.ObjectiveConfig$1.get(ObjectiveConfig.java:147) ~[lastaflute-0.9.8.jar:?]
        at org.lastaflute.core.direction.ObjectiveConfig.get(ObjectiveConfig.java:195) ~[lastaflute-0.9.8.jar:?]
        at org.codelibs.fess.mylasta.direction.FessConfig$SimpleImpl.getIndexFieldThumbnail(FessConfig.java:5739) ~[classes/:?]
        at org.codelibs.fess.helper.QueryHelper.init(QueryHelper.java:150) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:83) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.4.jar:?]
        ... 17 more
```

**Comment by jdeathe** [comment]
@micakovic - I had an similar issue which was resolved after adding the new elasticsearch plugin `elasticsearch-minhash` which is a new requirement for 11.2

```
/usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-minhash:5.4.1
```

Ref: http://fess.codelibs.org/11.2/install/install.html

**Comment by micakovic** [comment]
Updated plugins as suggested:

```bash
#!/bin/bash

plugins="analysis-fess analysis-ja analysis-kuromoji-neologd analysis-synonym configsync dataformat langfield minhash"

if [ "$#" -ne  "1" ]
then
    echo ""
    echo "You must supply the target ES version."
    echo "Example: Remove plugins, then install them for ES 5.3.1"
    echo "./update_fess_plugins.sh 5.3.1"
    echo ""
    exit 1;
else 
    for plugin in $plugins; do /usr/share/elasticsearch/bin/elasticsearch-plugin remove $plugin; done 
    for plugin in $plugins; do /usr/share/elasticsearch/bin/elasticsearch-plugin install "org.codelibs:elasticsearch-"$plugin":"$1; done
    echo ""
    echo "Remember to restart ES."
    exit 0
fi
```

Restarted ES, then:

```
/usr/share/elasticsearch/bin/elasticsearch-plugin list
analysis-fess
analysis-ja
analysis-kuromoji-neologd
analysis-synonym
configsync
dataformat
langfield
minhash
```

Here is the same thing with a little bit more detail:

```
 /usr/share/elasticsearch/bin/elasticsearch-plugin list --verbose
Plugins directory: /usr/share/elasticsearch/plugins
analysis-fess
- Plugin information:
Name: analysis-fess
Description: FessAnalysis Plugin for Elasticsearch
Version: 5.4.1
Native Controller: false
 * Classname: org.codelibs.elasticsearch.fess.FessAnalysisPlugin
analysis-ja
- Plugin information:
Name: analysis-ja
Description: This plugin provides an analysis library for Japanese.
Version: 5.4.1
Native Controller: false
 * Classname: org.codelibs.elasticsearch.ja.JaPlugin
analysis-kuromoji-neologd
- Plugin information:
Name: analysis-kuromoji-neologd
Description: Kuromoji with Neologd analysis support
Version: 5.4.1
Native Controller: false
 * Classname: org.codelibs.elasticsearch.kuromoji.neologd.KuromojiNeologdPlugin
analysis-synonym
- Plugin information:
Name: analysis-synonym
Description: This plugin provides N-Gram Synonym Tokenizer.
Version: 5.4.1
Native Controller: false
 * Classname: org.codelibs.elasticsearch.synonym.SynonymPlugin
configsync
- Plugin information:
Name: configsync
Description: ConfigSync plugin syncs up with configuration files in .configsync index.
Version: 5.4.1
Native Controller: false
 * Classname: org.codelibs.elasticsearch.configsync.ConfigSyncPlugin
dataformat
- Plugin information:
Name: dataformat
Description: This plugin provides several response formats.
Version: 5.4.1
Native Controller: false
 * Classname: org.codelibs.elasticsearch.df.DataFormatPlugin
langfield
- Plugin information:
Name: langfield
Description: This plugin provides langfield type.
Version: 5.4.1
Native Controller: false
 * Classname: org.codelibs.elasticsearch.langfield.LangFieldPlugin
minhash
- Plugin information:
Name: minhash
Description: This plugin provides b-bit minhash algorism.
Version: 5.4.1
Native Controller: false
 * Classname: org.codelibs.elasticsearch.minhash.MinHashPlugin
```

Fess still fails, interestingly:

```
2017-06-19 10:44:52,675 [localhost-startStop-1] ERROR Failed to initialize Lasta Di.
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
app.xml

[Namespace]
null
* * * * * * * * * */
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81) ~[lastaflute-0.9.8.jar:?]
        at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45) ~[lastaflute-0.9.8.jar:?]
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:136) [lastaflute-0.9.8.jar:?]
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94) [lastaflute-0.9.8.jar:?]
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285) [classes/:?]
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266) [classes/:?]
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108) [classes/:?]
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4590) [classes/:?]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233) [classes/:?]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [classes/:?]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [classes/:?]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [classes/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(init) of org.codelibs.fess.helper.QueryHelper, because org.lastaflute.core.direction.exception.ConfigPropertyNotFoundException: L
ook! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Not found the configuration property by the key.

[NotFound Property]
index.field.thumbnail

[Config Display]
FessConfig$SimpleImpl:{fess_config.properties, [fess_env_web.properties], ObjectiveConfig$1:{JavaPropertiesResult:{[domain.title, elasticsearch.cluster.name, elasticsearch.http.url, elasticsearch.transport.sniff, elasticsearch.transport.pi
ng_timeout, elasticsearch.transport.nodes_sampler_interval, app.cipher.algorism, app.cipher.key, app.digest.algorism, jvm.crawler.options, jvm.suggest.options, job.system.job.ids, job.template.title.web, job.template.title.file, job.templa
te.title.data, job.template.script, java.command.path, path.encoding, use.own.tmp.dir, max.log.output.length, supported.uploaded.js.extentions, supported.uploaded.css.extentions, supported.uploaded.media.extentions, supported.uploaded.file
s, supported.languages, api.access.token.length, api.access.token.required, crawler.document.max.site.length, crawler.document.site.encoding, crawler.document.unknown.hostname, crawler.document.use.site.encoding.on.english, crawler.documen
t.append.data, crawler.document.max.alphanum.term.size, crawler.document.max.symbol.term.size, crawler.document.duplicate.term.removed, crawler.document.space.chars, crawler.crawling.data.encoding, crawler.web.protocols, crawler.file.proto
cols, crawler.ignore.robots.txt, crawler.ignore.meta.robots, crawler.ignore.content.exception, crawler.metadata.content.excludes, crawler.metadata.name.mapping, crawler.document.html.content.xpath, crawler.document.html.lang.xpath, crawler.d
ocument.html.digest.xpath, crawler.document.html.canonical.xpath, crawler.document.html.pruned.tags, crawler.document.html.max.digest.length, crawler.document.file.name.encoding, crawler.document.file.no.title.label, crawler.document.file.ig
nore.empty.content, crawler.document.file.max.title.length, crawler.document.file.max.digest.length, crawler.document.file.append.meta.content, crawler.document.file.append.body.content, crawler.document.file.default.lang, crawler.document.c
ache.enabled, crawler.document.cache.max.size, crawler.document.cache.supported.mimetypes, crawler.document.cache.html.mimetypes, indexer.thread.dump.enabled, indexer.unprocessed.document.size, indexer.click.count.enabled, indexer.favorite.c
ount.enabled, indexer.webfs.commit.margin.time, indexer.webfs.max.empty.list.count, indexer.webfs.update.interval, indexer.webfs.max.document.cache.size, indexer.webfs.max.document.request.size, indexer.data.max.document.cache.size, indexer.
data.max.document.request.size, index.field.favorite_count, index.field.click_count, index.field.config_id, index.field.expires, index.field.url, index.field.doc_id, index.field.id, index.field.version, index.field.lang, index.field.has_cach
e, index.field.last_modified, index.field.anchor, index.field.segment, index.field.role, index.field.boost, index.field.created, index.field.timestamp, index.field.label, index.field.mimetype, index.field.parent_id, index.field.important_con
tent, index.field.content, index.field.cache, index.field.digest, index.field.title, index.field.host, index.field.site, index.field.content_length, index.field.filetype, index.field.filename, response.field.content_title, response.field.con
tent_description, response.field.url_link, response.field.site_path, index.document.search.index, index.document.update.index, index.document.type, index.document.suggest.index, index.document.crawler.index, index.admin.array.fields, index.a
dmin.date.fields, index.admin.integer.fields, index.admin.long.fields, index.admin.float.fields, index.admin.double.fields, index.admin.required.fields, index.search.timeout, index.scroll.search.timeout.timeout, index.index.timeout, index.bu
lk.timeout, index.delete.timeout, index.health.timeout, index.indices.timeout, query.max.length, query.geo.fields, query.browser.lang.parameter.name, query.replace.term.with.prefix.query, query.highlight.fragment.size, query.highlight.number
.of.fragments, query.highlight.type, query.max.search.result.offset, query.additional.response.fields, query.additional.api.response.fields, query.additional.cache.response.fields, query.additional.highlighted.fields, query.additional.search
.fields, query.additional.facet.fields, query.additional.sort.fields, query.additional.not.analyzed.fields, query.default.languages, query.language.mapping, query.boost.title, query.boost.title.lang, query.boost.content, query.boost.content.
lang, smb.role.from.file, smb.available.sid.types, index.backup.targets, form.admin.max.input.size, authentication.admin.users, authentication.admin.roles, role.search.default.permissions, role.search.default.display.permissions, role.search
.guest.permissions, role.search.user.prefix, role.search.group.prefix, role.search.role.prefix, cookie.default.path, cookie.default.expire, cookie.eternal.expire, cookie.remember.me.harbor.key, paging.page.size, paging.page.range.size, pagin
g.page.range.fill.limit, page.docboost.max.fetch.size, page.keymatch.max.fetch.size, page.labeltype.max.fetch.size, page.roletype.max.fetch.size, page.user.max.fetch.size, page.role.max.fetch.size, page.group.max.fetch.size, page.crawling.in
fo.param.max.fetch.size, page.crawling.info.max.fetch.size, page.data.config.max.fetch.size, page.web.config.max.fetch.size, page.file.config.max.fetch.size, page.duplicate.host.max.fetch.size, page.failure.url.max.fetch.size, page.favorite.
log.max.fetch.size, page.file.auth.max.fetch.size, page.web.auth.max.fetch.size, page.path.mapping.max.fetch.size, page.request.header.max.fetch.size, page.scheduled.job.max.fetch.size, page.search.field.log.max.fetch.size, page.elevate.word
.max.fetch.size, page.bad.word.max.fetch.size, page.dictionary.max.fetch.size, page.thumbnail.queue.max.fetch.size, paging.search.page.start, paging.search.page.size, paging.search.page.max.size, thumbnail.html.phantomjs.enabled, thumbnail.h
tml.phantomjs.max.height, thumbnail.html.phantomjs.keep.alive, thumbnail.html.phantomjs.window.width, thumbnail.html.phantomjs.window.height, thumbnail.html.phantomjs.thumbnail.width, thumbnail.html.phantomjs.thumbnail.height, thumbnail.html
.phantomjs.format, thumbnail.generator.targets, thumbnail.crawler.enabled, mail.from.name, mail.from.address, scheduler.target.name, scheduler.job.class, scheduler.concurrent.exec.mode, scheduler.monitor.interval, online.help.base.link, onli
ne.help.name.failureurl, online.help.name.elevateword, online.help.name.reqheader, online.help.name.dict.synonym, online.help.name.dict, online.help.name.dict.kuromoji, online.help.name.dict.seunjeon, online.help.name.dict.protwords, online.
help.name.dict.mapping, online.help.name.webconfig, online.help.name.searchlist, online.help.name.log, online.help.name.general, online.help.name.role, online.help.name.joblog, online.help.name.keymatch, online.help.name.wizard, online.help.
name.badword, online.help.name.pathmap, online.help.name.boostdoc, online.help.name.dataconfig, online.help.name.systeminfo, online.help.name.user, online.help.name.group, online.help.name.design, online.help.name.dashboard, online.help.name
.webauth, online.help.name.fileconfig, online.help.name.fileauth, online.help.name.labeltype, online.help.name.duplicatehost, online.help.name.scheduler, online.help.name.crawlinginfo, online.help.name.backup, online.help.name.upgrade, onlin
e.help.name.esreq, online.help.name.accesstoken, online.help.name.suggest, online.help.supported.langs, suggest.popular.word.seed, suggest.popular.word.tags, suggest.popular.word.fields, suggest.popular.word.excludes, suggest.popular.word.si
ze, suggest.popular.word.window.size, suggest.min.hit.count, suggest.field.contents, suggest.field.tags, suggest.field.roles, suggest.field.index.contents, suggest.update.request.interval, suggest.update.contents.limit.num.percentage, sugges
t.update.contents.limit.num, suggest.source.reader.scroll.size, suggest.popular.word.cache.size, suggest.popular.word.cache.expire, suggest.search.log.permissions, ldap.admin.enabled, ldap.admin.user.filter, ldap.admin.user.base.dn, ldap.adm
in.user.object.classes, ldap.admin.role.filter, ldap.admin.role.base.dn, ldap.admin.role.object.classes, ldap.admin.group.filter, ldap.admin.group.base.dn, ldap.admin.group.object.classes, ldap.admin.sync.password, ldap.max.username.length, 
ldap.role.search.user.enabled, ldap.role.search.group.enabled, ldap.role.search.role.enabled, ldap.attr.surname, ldap.attr.givenName, ldap.attr.employeeNumber, ldap.attr.mail, ldap.attr.telephoneNumber, ldap.attr.homePhone, ldap.attr.homePos
talAddress, ldap.attr.labeledURI, ldap.attr.roomNumber, ldap.attr.description, ldap.attr.title, ldap.attr.pager, ldap.attr.street, ldap.attr.postalCode, ldap.attr.physicalDeliveryOfficeName, ldap.attr.destinationIndicator, ldap.attr.internat
ionaliSDNNumber, ldap.attr.state, ldap.attr.employeeType, ldap.attr.facsimileTelephoneNumber, ldap.attr.postOfficeBox, ldap.attr.initials, ldap.attr.carLicense, ldap.attr.mobile, ldap.attr.postalAddress, ldap.attr.city, ldap.attr.teletexTerm
inalIdentifier, ldap.attr.x121Address, ldap.attr.businessCategory, ldap.attr.registeredAddress, ldap.attr.displayName, ldap.attr.preferredLanguage, ldap.attr.departmentNumber, ldap.attr.uidNumber, ldap.attr.gidNumber, ldap.attr.homeDirectory
, sso.type, spnego.logger.level, spnego.krb5.conf, spnego.login.conf, spnego.preauth.username, spnego.preauth.password, spnego.login.client.module, spnego.login.server.module, spnego.allow.basic, spnego.allow.unsecure.basic, spnego.prompt.nt
lm, spnego.allow.localhost, spnego.allow.delegation, oic.client.id, oic.client.secret, oic.auth.server.url, oic.redirect.url, oic.scope, oic.token.server.url, oic.default.roles, oic.default.groups, lasta_di.smart.deploy.mode, development.her
e, environment.title, framework.debug, time.adjust.time.millis, mail.send.mock, mail.smtp.server.main.host.and.port, mail.subject.test.prefix, mail.return.path]}}}@52ff877d
* * * * * * * * * */
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:83) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.4.jar:?]
        ... 17 more
Caused by: org.lastaflute.core.direction.exception.ConfigPropertyNotFoundException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Not found the configuration property by the key.

[NotFound Property]
index.field.thumbnail

[Config Display]
FessConfig$SimpleImpl:{fess_config.properties, [fess_env_web.properties], ObjectiveConfig$1:{JavaPropertiesResult:{[domain.title, elasticsearch.cluster.name, elasticsearch.http.url, elasticsearch.transport.sniff, elasticsearch.transport.ping
_timeout, elasticsearch.transport.nodes_sampler_interval, app.cipher.algorism, app.cipher.key, app.digest.algorism, jvm.crawler.options, jvm.suggest.options, job.system.job.ids, job.template.title.web, job.template.title.file, job.template.t
itle.data, job.template.script, java.command.path, path.encoding, use.own.tmp.dir, max.log.output.length, supported.uploaded.js.extentions, supported.uploaded.css.extentions, supported.uploaded.media.extentions, supported.uploaded.files, sup
ported.languages, api.access.token.length, api.access.token.required, crawler.document.max.site.length, crawler.document.site.encoding, crawler.document.unknown.hostname, crawler.document.use.site.encoding.on.english, crawler.document.append
.data, crawler.document.max.alphanum.term.size, crawler.document.max.symbol.term.size, crawler.document.duplicate.term.removed, crawler.document.space.chars, crawler.crawling.data.encoding, crawler.web.protocols, crawler.file.protocols, craw
ler.ignore.robots.txt, crawler.ignore.meta.robots, crawler.ignore.content.exception, crawler.metadata.content.excludes, crawler.metadata.name.mapping, crawler.document.html.content.xpath, crawler.document.html.lang.xpath, crawler.document.ht
ml.digest.xpath, crawler.document.html.canonical.xpath, crawler.document.html.pruned.tags, crawler.document.html.max.digest.length, crawler.document.file.name.encoding, crawler.document.file.no.title.label, crawler.document.file.ignore.empty
.content, crawler.document.file.max.title.length, crawler.document.file.max.digest.length, crawler.document.file.append.meta.content, crawler.document.file.append.body.content, crawler.document.file.default.lang, crawler.document.cache.enabl
ed, crawler.document.cache.max.size, crawler.document.cache.supported.mimetypes, crawler.document.cache.html.mimetypes, indexer.thread.dump.enabled, indexer.unprocessed.document.size, indexer.click.count.enabled, indexer.favorite.count.enabl
ed, indexer.webfs.commit.margin.time, indexer.webfs.max.empty.list.count, indexer.webfs.update.interval, indexer.webfs.max.document.cache.size, indexer.webfs.max.document.request.size, indexer.data.max.document.cache.size, indexer.data.max.d
ocument.request.size, index.field.favorite_count, index.field.click_count, index.field.config_id, index.field.expires, index.field.url, index.field.doc_id, index.field.id, index.field.version, index.field.lang, index.field.has_cache, index.f
ield.last_modified, index.field.anchor, index.field.segment, index.field.role, index.field.boost, index.field.created, index.field.timestamp, index.field.label, index.field.mimetype, index.field.parent_id, index.field.important_content, inde
x.field.content, index.field.cache, index.field.digest, index.field.title, index.field.host, index.field.site, index.field.content_length, index.field.filetype, index.field.filename, response.field.content_title, response.field.content_descr
iption, response.field.url_link, response.field.site_path, index.document.search.index, index.document.update.index, index.document.type, index.document.suggest.index, index.document.crawler.index, index.admin.array.fields, index.admin.date.
fields, index.admin.integer.fields, index.admin.long.fields, index.admin.float.fields, index.admin.double.fields, index.admin.required.fields, index.search.timeout, index.scroll.search.timeout.timeout, index.index.timeout, index.bulk.timeout
, index.delete.timeout, index.health.timeout, index.indices.timeout, query.max.length, query.geo.fields, query.browser.lang.parameter.name, query.replace.term.with.prefix.query, query.highlight.fragment.size, query.highlight.number.of.fragme
nts, query.highlight.type, query.max.search.result.offset, query.additional.response.fields, query.additional.api.response.fields, query.additional.cache.response.fields, query.additional.highlighted.fields, query.additional.search.fields, q
uery.additional.facet.fields, query.additional.sort.fields, query.additional.not.analyzed.fields, query.default.languages, query.language.mapping, query.boost.title, query.boost.title.lang, query.boost.content, query.boost.content.lang, smb.
role.from.file, smb.available.sid.types, index.backup.targets, form.admin.max.input.size, authentication.admin.users, authentication.admin.roles, role.search.default.permissions, role.search.default.display.permissions, role.search.guest.per
missions, role.search.user.prefix, role.search.group.prefix, role.search.role.prefix, cookie.default.path, cookie.default.expire, cookie.eternal.expire, cookie.remember.me.harbor.key, paging.page.size, paging.page.range.size, paging.page.ran
ge.fill.limit, page.docboost.max.fetch.size, page.keymatch.max.fetch.size, page.labeltype.max.fetch.size, page.roletype.max.fetch.size, page.user.max.fetch.size, page.role.max.fetch.size, page.group.max.fetch.size, page.crawling.info.param.m
ax.fetch.size, page.crawling.info.max.fetch.size, page.data.config.max.fetch.size, page.web.config.max.fetch.size, page.file.config.max.fetch.size, page.duplicate.host.max.fetch.size, page.failure.url.max.fetch.size, page.favorite.log.max.fe
tch.size, page.file.auth.max.fetch.size, page.web.auth.max.fetch.size, page.path.mapping.max.fetch.size, page.request.header.max.fetch.size, page.scheduled.job.max.fetch.size, page.search.field.log.max.fetch.size, page.elevate.word.max.fetch
.size, page.bad.word.max.fetch.size, page.dictionary.max.fetch.size, page.thumbnail.queue.max.fetch.size, paging.search.page.start, paging.search.page.size, paging.search.page.max.size, thumbnail.html.phantomjs.enabled, thumbnail.html.phanto
mjs.max.height, thumbnail.html.phantomjs.keep.alive, thumbnail.html.phantomjs.window.width, thumbnail.html.phantomjs.window.height, thumbnail.html.phantomjs.thumbnail.width, thumbnail.html.phantomjs.thumbnail.height, thumbnail.html.phantomjs
.format, thumbnail.generator.targets, thumbnail.crawler.enabled, mail.from.name, mail.from.address, scheduler.target.name, scheduler.job.class, scheduler.concurrent.exec.mode, scheduler.monitor.interval, online.help.base.link, online.help.na
me.failureurl, online.help.name.elevateword, online.help.name.reqheader, online.help.name.dict.synonym, online.help.name.dict, online.help.name.dict.kuromoji, online.help.name.dict.seunjeon, online.help.name.dict.protwords, online.help.name.
dict.mapping, online.help.name.webconfig, online.help.name.searchlist, online.help.name.log, online.help.name.general, online.help.name.role, online.help.name.joblog, online.help.name.keymatch, online.help.name.wizard, online.help.name.badwo
rd, online.help.name.pathmap, online.help.name.boostdoc, online.help.name.dataconfig, online.help.name.systeminfo, online.help.name.user, online.help.name.group, online.help.name.design, online.help.name.dashboard, online.help.name.webauth, 
online.help.name.fileconfig, online.help.name.fileauth, online.help.name.labeltype, online.help.name.duplicatehost, online.help.name.scheduler, online.help.name.crawlinginfo, online.help.name.backup, online.help.name.upgrade, online.help.nam
e.esreq, online.help.name.accesstoken, online.help.name.suggest, online.help.supported.langs, suggest.popular.word.seed, suggest.popular.word.tags, suggest.popular.word.fields, suggest.popular.word.excludes, suggest.popular.word.size, sugges
t.popular.word.window.size, suggest.min.hit.count, suggest.field.contents, suggest.field.tags, suggest.field.roles, suggest.field.index.contents, suggest.update.request.interval, suggest.update.contents.limit.num.percentage, suggest.update.c
ontents.limit.num, suggest.source.reader.scroll.size, suggest.popular.word.cache.size, suggest.popular.word.cache.expire, suggest.search.log.permissions, ldap.admin.enabled, ldap.admin.user.filter, ldap.admin.user.base.dn, ldap.admin.user.ob
ject.classes, ldap.admin.role.filter, ldap.admin.role.base.dn, ldap.admin.role.object.classes, ldap.admin.group.filter, ldap.admin.group.base.dn, ldap.admin.group.object.classes, ldap.admin.sync.password, ldap.max.username.length, ldap.role.
search.user.enabled, ldap.role.search.group.enabled, ldap.role.search.role.enabled, ldap.attr.surname, ldap.attr.givenName, ldap.attr.employeeNumber, ldap.attr.mail, ldap.attr.telephoneNumber, ldap.attr.homePhone, ldap.attr.homePostalAddress
, ldap.attr.labeledURI, ldap.attr.roomNumber, ldap.attr.description, ldap.attr.title, ldap.attr.pager, ldap.attr.street, ldap.attr.postalCode, ldap.attr.physicalDeliveryOfficeName, ldap.attr.destinationIndicator, ldap.attr.internationaliSDNN
umber, ldap.attr.state, ldap.attr.employeeType, ldap.attr.facsimileTelephoneNumber, ldap.attr.postOfficeBox, ldap.attr.initials, ldap.attr.carLicense, ldap.attr.mobile, ldap.attr.postalAddress, ldap.attr.city, ldap.attr.teletexTerminalIdenti
fier, ldap.attr.x121Address, ldap.attr.businessCategory, ldap.attr.registeredAddress, ldap.attr.displayName, ldap.attr.preferredLanguage, ldap.attr.departmentNumber, ldap.attr.uidNumber, ldap.attr.gidNumber, ldap.attr.homeDirectory, sso.type
, spnego.logger.level, spnego.krb5.conf, spnego.login.conf, spnego.preauth.username, spnego.preauth.password, spnego.login.client.module, spnego.login.server.module, spnego.allow.basic, spnego.allow.unsecure.basic, spnego.prompt.ntlm, spnego
.allow.localhost, spnego.allow.delegation, oic.client.id, oic.client.secret, oic.auth.server.url, oic.redirect.url, oic.scope, oic.token.server.url, oic.default.roles, oic.default.groups, lasta_di.smart.deploy.mode, development.here, environ
ment.title, framework.debug, time.adjust.time.millis, mail.send.mock, mail.smtp.server.main.host.and.port, mail.subject.test.prefix, mail.return.path]}}}@52ff877d
* * * * * * * * * */
        at org.lastaflute.core.direction.ObjectiveConfig.verifyPropertyValue(ObjectiveConfig.java:162) ~[lastaflute-0.9.8.jar:?]
        at org.lastaflute.core.direction.ObjectiveConfig$1.get(ObjectiveConfig.java:147) ~[lastaflute-0.9.8.jar:?]
        at org.lastaflute.core.direction.ObjectiveConfig.get(ObjectiveConfig.java:195) ~[lastaflute-0.9.8.jar:?]
        at org.codelibs.fess.mylasta.direction.FessConfig$SimpleImpl.getIndexFieldThumbnail(FessConfig.java:5739) ~[classes/:?]
        at org.codelibs.fess.helper.QueryHelper.init(QueryHelper.java:150) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:83) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.4.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.4.jar:?]
        ... 17 more
```

**Comment by marevol** [comment]
You need to merge fess_config.properties, not copy it from old one.
See [Upgrade guide](http://fess.codelibs.org/11.2/install/upgrade.html).

**Comment by micakovic** [comment]
Adding the missing plugin and merging fess_config.properties and fess_config.properties.rpmnew solves this issue.
